Repository utiasDSL/safe-control-gym, pull requests merged in 2022-07, with the labels that each got.

#38 Adding basic testing
  .github/workflows/push.yml
  examples/tracking.py
  examples/verbose_api.py
  experiments/pid/pid_experiment.py
  tests/test_build.py
  tests/test_examples/test_examples.py
  tests/test_experiments/test_pid/test_pid.py
Labels: enhancement

#39 Fixed gpmpc experiments to account for PR #35
  experiments/annual_reviews/figure6/config_overrides/gp_mpc_quad.yaml
  experiments/annual_reviews/figure6/config_overrides/gp_mpc_quad_training.yaml
  experiments/arxiv/quadrotor_performance/config_overrides/gpmpc_quadrotor_data_eff.yaml
Labels: enhancement

#41 Justin's 3D quad and test example
  examples/3d_quad.py
  examples/3d_quad.yaml
  safe_control_gym/controllers/pid/pid.py
  safe_control_gym/envs/gym_pybullet_drones/assets/gate.obj
  safe_control_gym/envs/gym_pybullet_drones/assets/gate.urdf
  safe_control_gym/envs/gym_pybullet_drones/assets/sphere.urdf
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor_utils.py
  safe_control_gym/math_and_models/transformations.py
Labels: enhancement

#45 Add DDPG baseline controller
  README.md
  safe_control_gym/controllers/__init__.py
  safe_control_gym/controllers/ddpg/__init__.py
  safe_control_gym/controllers/ddpg/ddpg.py
  safe_control_gym/controllers/ddpg/ddpg.yaml
  safe_control_gym/controllers/ddpg/ddpg_utils.py
  safe_control_gym/math_and_models/random_processes.py
  safe_control_gym/math_and_models/schedule.py
Labels: enhancement

#43 Fixing plot names in GPMPC arxiv experiments
  experiments/arxiv/cartpole_performance/utils/gpmpc_cartpole_control_performance.py
  experiments/arxiv/quadrotor_constraint/utils/gpmpc_quadrotor_impossible_traj.py
  experiments/arxiv/quadrotor_performance/utils/gpmpc_quadrotor_control_performance.py
  experiments/arxiv/quadrotor_performance/utils/gpmpc_quadrotor_data_eff.py
  experiments/arxiv/utils/gpmpc_plotting_utils.py
Labels: enhancement

#46 Changing Dependence on sklearn.PairwiseDistancesArgKmin
  experiments/annual_reviews/figure6/config_overrides/gp_mpc_quad.yaml
  experiments/annual_reviews/figure6/config_overrides/gp_mpc_quad_training.yaml
  experiments/annual_reviews/figure6/create_trained_gp_model.sh
  experiments/annual_reviews/figure6/gp_mpc_experiment.py
  experiments/annual_reviews/figure6/trained_gp_model/best_model_0.pth
  experiments/annual_reviews/figure6/trained_gp_model/best_model_1.pth
  experiments/annual_reviews/figure6/trained_gp_model/best_model_2.pth
  experiments/annual_reviews/figure6/trained_gp_model/best_model_3.pth
  experiments/annual_reviews/figure6/trained_gp_model/best_model_4.pth
  experiments/annual_reviews/figure6/trained_gp_model/best_model_5.pth
  experiments/annual_reviews/figure6/trained_gp_model/data.npz
  experiments/arxiv/quadrotor_performance/config_overrides/gpmpc_quadrotor_data_eff.yaml
  safe_control_gym/controllers/mpc/gp_mpc.py
  safe_control_gym/controllers/mpc/linear_mpc.py
  safe_control_gym/controllers/mpc/mpc.py
Labels: bug

#51 Fixing typos and other small problems
  .gitignore
  README.md
  examples/verbose_api.py
  safe_control_gym/controllers/ddpg/ddpg.py
  safe_control_gym/controllers/ppo/ppo.py
  safe_control_gym/controllers/sac/sac.py
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/envs/constraints.py
  safe_control_gym/envs/env_wrappers/record_episode_statistics.py
  tests/test_examples/test_examples.py
Labels: bug, documentation

#54 Two more small typos
  safe_control_gym/controllers/cbf/cbf_qp_utils.py
  safe_control_gym/controllers/mpc/gp_utils.py
Labels: bug

#52 Adding obs_goal_horizon to cartpole and fixing reward
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/envs/gym_control/cartpole.py
  safe_control_gym/envs/gym_control/cartpole.yaml
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.yaml
Labels: enhancement
