Repository utiasDSL/safe-control-gym, pull requests merged in 2022-08, with the labels that each got.

#58 3D quadrotor symoblic model
  safe_control_gym/envs/gym_pybullet_drones/base_aviary.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
  safe_control_gym/math_and_models/transformations.py
Labels: enhancement

#56 Updating the experiment class and related files
  safe_control_gym/controllers/base_controller.py
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/experiment.py
  safe_control_gym/math_and_models/metrics.py
Labels: enhancement

#53 Changing how actions are normalized and used in env
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/envs/constraints.py
  safe_control_gym/envs/gym_control/cartpole.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
Labels: bug, documentation

#63 Fixing typos
  README.md
  examples/verbose_api.yaml
  safe_control_gym/controllers/lqr/lqr_utils.py
  safe_control_gym/controllers/mpc/gp_mpc.py
  safe_control_gym/controllers/mpc/mpc.py
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
  walkthroughs/tutorial.md
Labels: enhancement

#69 Add metrics folder and MMD implementation
  safe_control_gym/experiment.py
  safe_control_gym/math_and_models/metrics/__init__.py
  safe_control_gym/math_and_models/metrics/performance_metrics.py
  safe_control_gym/math_and_models/metrics/similarity_metrics.py
Labels: enhancement

#68 Linting dev-experiment Files
  examples/quad_3D.py
  examples/tracking.py
  examples/verbose_api.py
  experiments/pid/pid_experiment.py
  safe_control_gym/controllers/base_controller.py
  safe_control_gym/controllers/pid/pid.py
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/envs/constraints.py
  safe_control_gym/envs/gym_control/cartpole.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
  safe_control_gym/experiment.py
  safe_control_gym/math_and_models/metrics/performance_metrics.py
  safe_control_gym/math_and_models/metrics/similarity_metrics.py
  tests/test_build.py
  tests/test_examples/test_examples.py
  tests/test_experiments/test_pid/test_pid.py
Labels: documentation

#76 Competition (no firmware) test
  competition/getting_started.py
  tests/test_competition/test_competition.py
Labels: enhancement

#71 Add similarity metrics: MSE(ED), DTW, LCSS, EDR, FD
  .gitignore
  experiments/metrics/config_overrides/cartpole/base.yaml
  experiments/metrics/config_overrides/cartpole/ppo.yaml
  experiments/metrics/config_overrides/quad_track_2d/base.yaml
  experiments/metrics/config_overrides/quad_track_2d/variant.yaml
  experiments/metrics/test_metric.py
  experiments/metrics/test_metric_run.sh
  safe_control_gym/experiment.py
  safe_control_gym/math_and_models/metrics/similarity_metrics.py
  safe_control_gym/math_and_models/symbolic_systems.py
  safe_control_gym/math_and_models/transformations.py
Labels: enhancement

#75 Linting some docstrings
  experiments/arxiv/cartpole_constraint/utils/gpmpc_cartpole_constraint.py
  experiments/arxiv/cartpole_performance/utils/gpmpc_cartpole_control_performance.py
  experiments/arxiv/cartpole_performance/utils/gpmpc_cartpole_data_eff.py
  experiments/arxiv/cartpole_robustness/utils/gpmpc_cartpole_input_white_noise_robustness.py
  experiments/arxiv/cartpole_robustness/utils/gpmpc_cartpole_pole_length_robustness.py
  experiments/arxiv/quadrotor_constraint/utils/gpmpc_quadrotor_impossible_traj.py
  experiments/arxiv/quadrotor_performance/utils/gpmpc_quadrotor_control_performance.py
  experiments/arxiv/quadrotor_performance/utils/gpmpc_quadrotor_data_eff.py
  safe_control_gym/controllers/mpc/gp_utils.py
  safe_control_gym/controllers/rarl/rap.py
  safe_control_gym/controllers/rarl/rarl.py
  safe_control_gym/utils/plotting.py
Labels: bug, documentation

#74 Adding safety filters
  README.md
  experiments/annual_reviews/figure8/config_overrides/cartpole_config.yaml
  experiments/annual_reviews/figure8/config_overrides/config_mpsc_cartpole.yaml
  experiments/annual_reviews/figure8/config_overrides/mpsc_config.yaml
  experiments/annual_reviews/figure8/config_overrides/ppo_config.yaml
  experiments/annual_reviews/figure8/config_overrides/unsafe_ppo_config.yaml
  experiments/annual_reviews/figure8/create_fig8.sh
  experiments/annual_reviews/figure8/create_unsafe_ppo_model.sh
  experiments/annual_reviews/figure8/mpsc_data.pkl
  experiments/annual_reviews/figure8/mpsc_experiment.py
  safe_control_gym/__init__.py
  safe_control_gym/controllers/__init__.py
  safe_control_gym/controllers/mpsc/mpsc.py
  safe_control_gym/controllers/mpsc/mpsc.yaml
  safe_control_gym/controllers/mpsc/mpsc_utils.py
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/envs/constraints.py
  safe_control_gym/envs/gym_control/cartpole.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
  safe_control_gym/experiment.py
  safe_control_gym/safety_filters/__init__.py
  safe_control_gym/safety_filters/base_safety_filter.py
  safe_control_gym/safety_filters/mpsc/__init__.py
  safe_control_gym/safety_filters/mpsc/linear_mpsc.py
  safe_control_gym/safety_filters/mpsc/mpsc.py
  safe_control_gym/safety_filters/mpsc/mpsc.yaml
  safe_control_gym/safety_filters/mpsc/mpsc_cost_function/abstract_cost.py
  safe_control_gym/safety_filters/mpsc/mpsc_cost_function/one_step_cost.py
  safe_control_gym/safety_filters/mpsc/mpsc_utils.py
  safe_control_gym/utils/configuration.py
  tests/test_build.py
  tests/test_experiments/test_annual_reviews/test_figure8.py
  tests/test_experiments/test_lqr.py
  tests/test_experiments/test_pid.py
  walkthroughs/tutorial.md
Labels: enhancement

#80 Mpsc tests
  .gitignore
  experiments/mpsc/config_overrides/cartpole/cartpole_stab.yaml
  experiments/mpsc/config_overrides/cartpole/cartpole_track.yaml
  experiments/mpsc/config_overrides/cartpole/linear_mpsc_cartpole.yaml
  experiments/mpsc/config_overrides/cartpole/lqr_cartpole.yaml
  experiments/mpsc/config_overrides/cartpole/nl_mpsc_cartpole.yaml
  experiments/mpsc/config_overrides/cartpole/ppo_cartpole.yaml
  experiments/mpsc/config_overrides/cartpole/sac_cartpole.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/linear_mpsc_quadrotor_2D.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/lqr_quadrotor_2D.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/nl_mpsc_quadrotor_2D.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/pid_quadrotor_2D.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/ppo_quadrotor_2D.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/quadrotor_2D_stab.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/quadrotor_2D_track.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/sac_quadrotor_2D.yaml
  experiments/mpsc/config_overrides/quadrotor_3D/linear_mpsc_quadrotor_3D.yaml
  experiments/mpsc/config_overrides/quadrotor_3D/pid_quadrotor_3D.yaml
  experiments/mpsc/config_overrides/quadrotor_3D/quadrotor_3D_stab.yaml
  experiments/mpsc/models/linear_mpsc_cartpole.pkl
  experiments/mpsc/models/linear_mpsc_quadrotor_2D.pkl
  experiments/mpsc/models/ppo_model_cartpole_stab.pt
  experiments/mpsc/models/ppo_model_cartpole_track.pt
  experiments/mpsc/models/ppo_model_quadrotor_2D_stab.pt
  experiments/mpsc/models/ppo_model_quadrotor_2D_track.pt
  experiments/mpsc/models/sac_model_cartpole_stab.pt
  experiments/mpsc/models/sac_model_cartpole_track.pt
  experiments/mpsc/models/sac_model_quadrotor_2D_stab.pt
  experiments/mpsc/models/sac_model_quadrotor_2D_track.pt
  experiments/mpsc/mpsc_experiment.py
  experiments/mpsc/test_mpsc.sh
  experiments/mpsc/train_rl_model.sh
  tests/test_experiments/test_mpsc.py
Labels: documentation

#79 Tall and low gates
  README.md
  competition/edit_this.py
  competition/getting_started.py
  competition/getting_started.yaml
  safe_control_gym/envs/gym_pybullet_drones/assets/low_portal.urdf
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
Labels: enhancement

#84 Done-on-collision and timing
  README.md
  competition/competition_utils.py
  competition/edit_this.py
  competition/getting_started.py
  competition/getting_started.yaml
  safe_control_gym/envs/gym_pybullet_drones/Logger.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
Labels: enhancement, Competition

#85 initial dev branch commit
  competition/getting_started.py
  safe_control_gym/envs/constraints.py
Labels: bug, enhancement, Competition

#86 Environment re-seeding arg
  competition/getting_started.yaml
  safe_control_gym/envs/benchmark_env.py
Labels: enhancement, competition
