Repository utiasDSL/safe-control-gym, pull requests merged in 2022-09, with the labels that each got.

#87 Evaluation
  README.md
  competition/edit_this.py
  competition/getting_started.py
  pyproject.toml
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
Labels: enhancement, competition

#77 Allow varying env model priors for PID, LQR, and MPC
  README.md
  experiments/pid/config_overrides/pid.yaml
  experiments/pid/config_overrides/quadrotor_stabilization.yaml
  experiments/pid/config_overrides/quadrotor_tracking.yaml
  experiments/pid/pid_experiment.sh
  safe_control_gym/controllers/base_controller.py
  safe_control_gym/controllers/pid/pid.py
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/envs/gym_control/cartpole.py
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
  safe_control_gym/math_and_models/symbolic_systems.py
Labels: bug, enhancement

#92 Adding priors to MPSC and CBF
  examples/verbose_api.yaml
  experiments/annual_reviews/figure8/config_overrides/mpsc_config.yaml
  experiments/cbf/config_overrides/cbf_config.yaml
  experiments/cbf/config_overrides/cbf_nn_config.yaml
  experiments/mpsc/config_overrides/cartpole/linear_mpsc_cartpole.yaml
  experiments/mpsc/config_overrides/cartpole/nl_mpsc_cartpole.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/linear_mpsc_quadrotor_2D.yaml
  experiments/mpsc/config_overrides/quadrotor_2D/nl_mpsc_quadrotor_2D.yaml
  experiments/mpsc/config_overrides/quadrotor_3D/linear_mpsc_quadrotor_3D.yaml
  experiments/pid/config_overrides/pid.yaml
  experiments/pid/pid_experiment.py
  safe_control_gym/controllers/base_controller.py
  safe_control_gym/controllers/pid/pid.py
  safe_control_gym/envs/gym_control/cartpole.py
  safe_control_gym/safety_filters/base_safety_filter.py
  safe_control_gym/safety_filters/cbf/cbf.py
  safe_control_gym/safety_filters/cbf/cbf.yaml
  safe_control_gym/safety_filters/cbf/cbf_nn.py
  safe_control_gym/safety_filters/cbf/cbf_nn.yaml
  safe_control_gym/safety_filters/mpsc/linear_mpsc.py
  safe_control_gym/safety_filters/mpsc/mpsc.py
  safe_control_gym/safety_filters/mpsc/mpsc.yaml
Labels: bug, enhancement

#88 Constraint Evaluation Rounding Errors
  safe_control_gym/envs/benchmark_env.py
  safe_control_gym/envs/constraints.py
Labels: bug
