Repository utiasDSL/safe-control-gym, pull requests merged in 2025-05, with the labels that each got.

#190 Minor changes to examples
  .pre-commit-config.yaml
  examples/mpc/mpc_experiment.py
  examples/pid/pid_experiment.py
  safe_control_gym/controllers/lqr/ilqr.py
  safe_control_gym/experiments/base_experiment.py
Labels: enhancement

#196 MPC Linting and Documentation
  .gitignore
  .pre-commit-config.yaml
  safe_control_gym/controllers/base_controller.py
  safe_control_gym/controllers/mpc/gp_mpc.py
  safe_control_gym/controllers/mpc/gp_mpc.yaml
  safe_control_gym/controllers/mpc/gp_utils.py
  safe_control_gym/controllers/mpc/linear_mpc.py
  safe_control_gym/controllers/mpc/linear_mpc.yaml
  safe_control_gym/controllers/mpc/mpc.py
  safe_control_gym/controllers/mpc/mpc.yaml
  safe_control_gym/controllers/mpc/mpc_acados.yaml
  safe_control_gym/controllers/mpc/mpc_utils.py
  safe_control_gym/controllers/safe_explorer/safe_explorer_utils.py
  safe_control_gym/controllers/safe_explorer/safe_ppo.py
Labels: documentation, linting

#197 General refactoring of MPC code and especially mpc_acados
  examples/mpc/mpc_experiment.sh
  safe_control_gym/controllers/mpc/gp_mpc.py
  safe_control_gym/controllers/mpc/linear_mpc.py
  safe_control_gym/controllers/mpc/mpc.py
  safe_control_gym/controllers/mpc/mpc_acados.py
  safe_control_gym/utils/utils.py
Labels: linting

#202 Create per-instance copy of quadrotor randomization attributes
  safe_control_gym/envs/gym_pybullet_drones/quadrotor.py
Labels: bug
